//
//  ExchangePresenter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 17.11.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExchangePresentationLogic
{
  func presentSomething(response: Exchange.Something.Response)
}

class ExchangePresenter: ExchangePresentationLogic
{
  weak var viewController: ExchangeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Exchange.Something.Response)
  {
    let viewModel = Exchange.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
