//
//  ExchangeInteractor.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 17.11.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExchangeBusinessLogic
{
  func doSomething(request: Exchange.Something.Request)
}

protocol ExchangeDataStore
{
  //var name: String { get set }
}

class ExchangeInteractor: ExchangeBusinessLogic, ExchangeDataStore
{
  var presenter: ExchangePresentationLogic?
  var worker: ExchangeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Exchange.Something.Request)
  {
    worker = ExchangeWorker()
    worker?.doSomeWork()
    
    let response = Exchange.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
