//
//  ExchangeRouter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 17.11.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ExchangeRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    
    func showPalonixModule()
}

protocol ExchangeDataPassing
{
  var dataStore: ExchangeDataStore? { get }
}

class ExchangeRouter: NSObject, ExchangeRoutingLogic, ExchangeDataPassing
{
  weak var viewController: ExchangeViewController?
  var dataStore: ExchangeDataStore?
  
  // MARK: Routing
    
    func showPalonixModule() {
//        let palonix = PalonixVC()
        
//        viewController?.present(palonix, animated: true)
    }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ExchangeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ExchangeDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
