//
//  PairsPresenter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 06.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PairsPresentationLogic
{
//  func presentSomething(response: Pairs.Something.Response)
    func presentPairs(response: Pairs.Something.Response)
    func presentError(response: Pairs.Something.Response)
}

class PairsPresenter: PairsPresentationLogic
{
    
  weak var viewController: PairsDisplayLogic?
  
  // MARK: Do something
  
    func presentPairs(response: Pairs.Something.Response) {
        let viewModel = Pairs.Something.ViewModel(pairs: response.pairs, errorMessage: nil)
        viewController?.displayPairs(viewModel: viewModel)
    }
    
    func presentError(response: Pairs.Something.Response) {
        let viewModel = Pairs.Something.ViewModel(pairs: nil, errorMessage: response.errorMessage)
        viewController?.displayAllert(viewModel: viewModel)
    }
}
