//
//  PairsInteractor.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 06.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PairsBusinessLogic
{
  func doSomething(request: Pairs.Something.Request)
}

protocol PairsDataStore
{
  //var name: String { get set }
}

class PairsInteractor: PairsBusinessLogic, PairsDataStore
{
  var presenter: PairsPresentationLogic?
  var worker: PairsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Pairs.Something.Request)
  {
    worker = PairsWorker()
    worker?.doSomeWork()
    
    let response = Pairs.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
