//
//  PairsRouter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 06.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PairsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToTrade(pairName: String)
}

protocol PairsDataPassing
{
  var dataStore: PairsDataStore? { get }
}

class PairsRouter: NSObject, PairsRoutingLogic, PairsDataPassing
{
  weak var viewController: PairsViewController?
  var dataStore: PairsDataStore?
  
  // MARK: Routing
  
    
    func routeToTrade(pairName: String){
        DispatchQueue.main.async {
            let tradeVC = TradeViewController()
            tradeVC.title = pairName
            self.viewController?.navigationController?.pushViewController(tradeVC, animated: true)
        }
    }

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: PairsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: PairsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
