//
//  PairsInteractor.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 06.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PairsBusinessLogic
{
//  func doSomething(request: Pairs.Something.Request)
    func getPairs()
}

protocol PairsDataStore
{
  //var name: String { get set }
}

class PairsInteractor: PairsBusinessLogic, PairsDataStore
{
  var presenter: PairsPresentationLogic?
  var worker: PairsWorker?
    let utils: NetworkService?
    let service: ApiService?
    let dataBase = PairDao()
    
    init() {
        utils = UtilsService()
        service = PoloniexApiService(utilService: utils!)
    }
  
  // MARK: Do something
  
    func getPairs() {
        if Reachability.isConnectedToNetwork(){
            service!.getPairs { result in
                switch result {
                case .success(let data):
                    self.dataBase.clear(){_ in}
                    self.dataBase.saveAll(model: data){_ in}
                    let response = Pairs.Something.Response.init(pairs: data, errorMessage: nil)
                    self.presenter?.presentPairs(response: response)
                    print("")
                case .failure(let error):
                    let response = Pairs.Something.Response(pairs: nil, errorMessage: error.error)
                    self.presenter?.presentError(response: response)
                }
            }
        }else{
            dataBase.getAll(){
                result in
                switch result {
                case .success(let data):
                    if let unData = data, unData.count != 0 {
                        let response = Pairs.Something.Response.init(pairs: unData, errorMessage: nil)
                        self.presenter?.presentPairs(response: response)
                    }else{
                        let response = Pairs.Something.Response(pairs: nil, errorMessage: "Empty pairs")
                        self.presenter?.presentError(response: response)
                    }
                case .failure(let error):
                    print("")
                    let response = Pairs.Something.Response(pairs: nil, errorMessage: error.error)
                    self.presenter?.presentError(response: response)
                }
                
            }
        }
    }
  
}
