//
//  ProfilePresenter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 04.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic
{
    func presentError(response: Profile.Something.Response)
    func presentMessage(response: Profile.Something.Response)
    func presentClear()
}

class ProfilePresenter: ProfilePresentationLogic
{
    
    
  weak var viewController: ProfileDisplayLogic?
  
  // MARK: Do something
  
    func presentError(response: Profile.Something.Response){
        viewController?.displayError(viewModel: Profile.Something.ViewModel(errorMessage: response.errorMessage, message: response.message))
    }
    
    func presentMessage(response: Profile.Something.Response) {
        viewController?.displaySuccessAlert(viewModel: Profile.Something.ViewModel(errorMessage: nil, message: response.message))
    }
    
    func presentClear(){
        viewController?.displayClear()
    }
}
