//
//  ProfileModels.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 04.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        let apiKey: String
        let secretKey: String
    }
    struct Response
    {
        let errorMessage: String?
        let message: String?
    }
    struct ViewModel
    {
        let errorMessage: String?
        let message: String?
    }
  }
}
