//
//  TradeInteractor.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 04.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TradeBusinessLogic
{
  func doSomething(request: Trade.Something.Request)
}

protocol TradeDataStore
{
  //var name: String { get set }
}

class TradeInteractor: TradeBusinessLogic, TradeDataStore
{
  var presenter: TradePresentationLogic?
  var worker: TradeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Trade.Something.Request)
  {
    worker = TradeWorker()
    worker?.doSomeWork()
    
    let response = Trade.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
