//
//  TradePresenter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 04.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TradePresentationLogic
{
  func presentSomething(response: Trade.Something.Response)
}

class TradePresenter: TradePresentationLogic
{
  weak var viewController: TradeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Trade.Something.Response)
  {
    let viewModel = Trade.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
