//
//  WalletPresenter.swift
//  ExchangeApp
//
//  Created by Юрий Нориков on 03.12.2019.
//  Copyright (c) 2019 norikoff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletPresentationLogic
{
    func presentWallet(response: Wallet.Something.Response)
    func presentError(response: Wallet.Something.Response)
}

class WalletPresenter: WalletPresentationLogic
{
    
    weak var viewController: WalletDisplayLogic?
    
    // MARK: Do something
    
    func presentWallet(response: Wallet.Something.Response) {
        let viewModel = Wallet.Something.ViewModel(wallet: response.wallet, errorMessage: nil)
        viewController?.displayWallet(viewModel: viewModel)
    }
    
    func presentError(response: Wallet.Something.Response) {
        print("error")
        let viewModel = Wallet.Something.ViewModel(wallet: nil, errorMessage: response.errorMessage)
        viewController?.displayAllert(viewModel: viewModel)
    }
    
}
